"""posts table

Revision ID: 3b5ded0f18d7
Revises: 14dd3c75ac4c
Create Date: 2026-04-14 12:12:12.947613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b5ded0f18d7'
down_revision = '14dd3c75ac4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_password_hash'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_password_hash'), ['password_hash'], unique=1)

    # ### end Alembic commands ###
